### ISSUE TITLE
Honor Ordering of DI for xml

### ISSUE THREAD

**Issue by yT0n1** [bptlab/chor-js#159]
There were changes made in bpmn-js 6.3.4 https://github.com/bpmn-io/bpmn-js/blob/develop/CHANGELOG.md#634 fixing an issue from https://github.com/bpmn-io/bpmn-js/issues/985
This broke our export due to the relationship between participants and their multiple DIs.
We disabled this reordering, however, in the long run this is something we should fix to suit the standard.

**Comment by jan-ladleif** [comment]
I think the core problem is in [this line](https://github.com/bpmn-io/bpmn-js/blob/8f190bb53c0f86f0d5a82bd9853f1006ee89138e/lib/features/di-ordering/BpmnDiOrdering.js#L31).

It calls `getDi` for each element, which obviously does not work for participants.
So we have to somehow overwrite that with the following exceptions:

- If the element is a `Participant`, return nothing (`undefined`).
- If the element is a `ChoreographyActivity`, also return the participant band DIs (`[di1, di2, ...]`).
- Otherwise, return the singular di (`di`).

We should also check whether this works for our re-implementation of `Message`s, their `selfAndAllChildren` function might not be aware of the fact that we use them differently.
