### ISSUE TITLE
Color API not working

### ISSUE THREAD

**Issue by CaptnIglo** [bptlab/chor-js#169]
Hello,
I tried to use the color API. The colors will be inserted into the xml, yet the colors are not displayed/rendered. I was not sure if the color API is meant to work. Would be great to get any feedback on that.

**Comment by jan-ladleif** [comment]
Hi @CaptnIglo, thank you for your interest in chor-js! 🙂
Could you check whether your issue is the same as this one https://github.com/bptlab/chor-js/issues/152?
If so, that is a current limitation of the renderer, unfortunately.

**Comment by CaptnIglo** [comment]
Hey @jan-ladleif , thank you for your fast reply. It seems like it is the same issue. Will colors be reintroduced in the future?

**Comment by jan-ladleif** [comment]
@CaptnIglo Well, since it's been on our backlog for a while, I went ahead and implemented it, see the PR here: https://github.com/bptlab/chor-js/pull/171 🙂
Please feel free to comment, test it out, and make suggestions!

Otherwise, we'll have to do some more tests tomorrow, and will then publish a new release of `chor-js` in a few days.

**Comment by CaptnIglo** [comment]
Hey, @jan-ladleif these are great news. Thank you very much for taking your time to implement this feature. I will try it out during the next days.  :)
